const form = document.querySelector("#scanForm");
const button = document.querySelector("#scanButton");
const statusPill = document.querySelector("#scanStatus");
const metricTarget = document.querySelector("#metricTarget");
const metricOpen = document.querySelector("#metricOpen");
const metricChecked = document.querySelector("#metricChecked");
const metricDuration = document.querySelector("#metricDuration");
const summaryStrip = document.querySelector("#summaryStrip");
const detailCard = document.querySelector("#detailCard");

let lastReport = "";

function normalizeTarget(value) {
  return value.trim().replace(/\/+$/, "");
}

function parsePorts(value) {
  const ports = new Set();

  value
    .split(",")
    .map((part) => part.trim())
    .filter(Boolean)
    .forEach((part) => {
      if (part.includes("-")) {
        const [start, end] = part.split("-").map((item) => Number(item.trim()));
        if (Number.isInteger(start) && Number.isInteger(end)) {
          const low = Math.max(1, Math.min(start, end));
          const high = Math.min(65535, Math.max(start, end));
          for (let port = low; port <= high; port += 1) ports.add(port);
        }
        return;
      }

      const port = Number(part);
      if (Number.isInteger(port) && port >= 1 && port <= 65535) ports.add(port);
    });

  return [...ports].sort((a, b) => a - b);
}

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function riskLevel(openRows) {
  const highRisk = openRows.some((row) =>
    [21, 23, 445, 3389, 5900, 6379, 27017].includes(Number(row.port))
  );
  if (highRisk) return "High";
  if (openRows.length > 4) return "Medium";
  if (openRows.length > 0) return "Low";
  return "Informational";
}

function serviceLabel(row) {
  const banner = row.banner ? ` - ${row.banner}` : "";
  return `${row.host}:${row.port}/${row.service} (${row.confidence})${banner}`;
}

function buildReport(result) {
  const services = result.openPorts.map(serviceLabel).join(", ") || "None";
  const risk = riskLevel(result.openPorts);

  return [
    "SecureProbe Security Assessment Report",
    "",
    `Target: ${result.target}`,
    `Resolved target(s): ${result.resolvedTargets.join(", ")}`,
    `Checked TCP sockets: ${result.checkedPorts}`,
    `Open TCP ports: ${result.openCount}`,
    `Closed or filtered TCP ports: ${result.closedCount}`,
    `Duration: ${result.duration}`,
    `Detected services: ${services}`,
    `Exposure rating: ${result.exposureRating || risk}`,
    `PDF report: ${result.pdfReport || "Generated by server"}`,
    "",
    "Assessment Summary",
    result.openCount
      ? `The scanner confirmed ${result.openCount} reachable TCP service(s): ${services}. Results represent what is reachable from this machine at scan time.`
      : "No open TCP ports were confirmed in the selected scope from this machine at scan time.",
    "",
    "Recommendations",
    "1. Confirm every exposed service has a business requirement.",
    "2. Disable unused ports and restrict administrative services with firewall rules.",
    "3. Keep service versions patched and review TLS configuration for HTTPS endpoints.",
    "4. Repeat the scan after remediation and preserve reports for audit evidence.",
  ].join("\n");
}

function renderResults(result) {
  const openList = result.openPorts.map((row) => `${row.host}:${row.port}`).join(", ");
  const risk = riskLevel(result.openPorts);
  const safeTarget = escapeHtml(result.target);
  const findings = Array.isArray(result.findings) ? result.findings : [];

  metricTarget.textContent = result.target;
  metricOpen.textContent = String(result.openCount);
  metricChecked.textContent = String(result.checkedPorts);
  metricDuration.textContent = result.duration;

  summaryStrip.textContent = result.openCount
    ? `Open TCP ports for ${result.target}: ${openList}.`
    : `No open TCP ports found for ${result.target} in the selected list.`;

  lastReport = buildReport(result);

  const rows = result.openPorts
    .map(
      (row) => `
        <div class="port-row">
          <span class="port-chip">${escapeHtml(row.port)}</span>
          <span class="service-name">
            ${escapeHtml(row.host)} - ${escapeHtml(row.service)}
            ${row.banner ? `<small>${escapeHtml(row.banner)}</small>` : ""}
          </span>
        </div>
      `
    )
    .join("");

  detailCard.innerHTML = `
    <div class="detail-grid">
      <div class="detail-item">
        <span>Target</span>
        <strong>${safeTarget}</strong>
      </div>
      <div class="detail-item">
        <span>Open ports</span>
        <strong>${escapeHtml(result.openCount)}</strong>
      </div>
      <div class="detail-item">
        <span>Closed or filtered</span>
        <strong>${escapeHtml(result.closedCount)}</strong>
      </div>
      <div class="detail-item">
        <span>Duration</span>
        <strong>${escapeHtml(result.duration)}</strong>
      </div>
    </div>
    <p class="result-note">${escapeHtml(summaryStrip.textContent)}</p>
    <div class="ports-list">
      <h3>Open ports</h3>
      ${
        result.openPorts.length
          ? rows
          : '<p class="empty-state">No open ports were detected in this scan profile.</p>'
      }
    </div>
    <div class="report-block">
      <h3>Security assessment</h3>
      <p><strong>Exposure rating:</strong> ${escapeHtml(result.exposureRating || risk)}</p>
      <p>${
        result.openPorts.length
          ? "The scanner confirmed live TCP connections. Review each exposed service and verify it is required, patched, and monitored."
          : "The selected port set did not expose reachable services from this machine at scan time."
      }</p>
      <div class="findings-list">
        ${findings.map((finding) => `
          <div class="finding-row">
            <span>${escapeHtml(finding.severity)}</span>
            <strong>${escapeHtml(finding.title)}</strong>
            <small>${escapeHtml(finding.recommendation)}</small>
          </div>
        `).join("")}
      </div>
      <div class="report-actions">
        <button type="button" id="downloadReport">VIEW Report</button>
        <button type="button" class="ghost-button" id="copyReport">Copy summary</button>
      </div>
    </div>
  `;

  const downloadButton = document.querySelector("#downloadReport");

if (downloadButton) {
  downloadButton.addEventListener("click", () => {
    downloadReport(result.pdfReport);
  });
}
  document.querySelector("#copyReport").addEventListener("click", copyReport);
}

function downloadReport(pdfUrl) {
  if (pdfUrl) {
    window.open(pdfUrl, "_blank", "noopener");
    return;
  }
  const blob = new Blob([lastReport], { type: "text/plain;charset=utf-8" });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = "secureprobe-assessment-report.txt";
  link.click();
  URL.revokeObjectURL(link.href);
}

async function copyReport() {
  const copyButton = document.querySelector("#copyReport");
  await navigator.clipboard.writeText(lastReport);
  copyButton.textContent = "Copied";
  setTimeout(() => {
    copyButton.textContent = "Copy summary";
  }, 1300);
}

async function scanTarget({ target, ports, timeout, threads }) {
  const response = await fetch("/api/scan", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ target, ports, timeout, threads }),
  });
  const payload = await response.json();
  if (!response.ok) {
    throw new Error(payload.error || "Scan failed.");
  }
  return payload;
}

form.addEventListener("submit", async (event) => {
  event.preventDefault();

  const formData = new FormData(form);
  const target = normalizeTarget(String(formData.get("target") || ""));
  const portsText = String(formData.get("ports") || "");
  const timeout = Number(formData.get("timeout"));
  const threads = Number(formData.get("threads"));
  const ports = parsePorts(portsText);

  if (!target || ports.length === 0) {
    summaryStrip.textContent = "Enter a valid target and at least one TCP port.";
    return;
  }

  button.disabled = true;
  button.textContent = "Scanning...";
  statusPill.textContent = "Scanning";
  statusPill.className = "status-pill scanning";
  summaryStrip.textContent = "Running a real TCP scan from this machine...";

  try {
    const result = await scanTarget({ target, ports: portsText, timeout, threads });
    renderResults(result);
    statusPill.textContent = "Scan complete";
    statusPill.className = "status-pill done";
  } catch (error) {
    summaryStrip.textContent = error.message;
    statusPill.textContent = "Scan failed";
    statusPill.className = "status-pill";
  } finally {
    button.disabled = false;
    button.textContent = "Check open ports";
  }
});
